from solution.first_question_sol import sortedarray
from solution.second_question.solution import remove_non_int
from solution.third_question_sol import calculate_avg
from solution.fifth_ques_sol import fabn as fabnicco_Series